server:
  port: 28080

spring:
  datasource:
    #    url: jdbc:mysql://localhost:3307/ad
    url: jdbc:mysql://localhost:3306/queue-system
    username: root
    password: caroline
#    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
